// src/base/SongList/index.jsx
import styles from './style.module.scss'

const SongList = ({songs, rank}) => {

  const getDesc = (song) => {
    return `${song.singer}·${song.album}`
  }

  return (
    <ul className={styles.songList}>
      {songs?.map((song, index) => {
        return (
          <li 
          className={styles.item}
          key={song.id}
          // onClick={() => selectItem(song, index)}
          >
            {rank && (
              <div className={styles.rank}>
                {/* <div className={getRankCls(index)}>
                  { getRankText(index) }
                </div> */}
              </div>
            )}
            <div className={styles.content}>
              <h2 className={styles.name}>{song.name}</h2>
              <p className={styles.desc}>{getDesc(song)}</p>
            </div>
          </li>
        )
      })}
    </ul>
  )
}

export default SongList

// src/base/SongList/song-list.vue
<template>
  <ul class="song-list">
    <li
      class="item"
      v-for="(song, index) in props.songs"
      :key="song.id"
      @click="selectItem(song, index)"
    >
      <div class="rank" v-if="props.rank">
        <span :class="getRankCls(index)">{{ getRankText(index) }}</span>
      </div>
      <div class="content">
        <h2 class="name">{{song.name}}</h2>
        <p class="desc">{{getDesc(song)}}</p>
      </div>
    </li>
  </ul>
</template>

<script setup>
  const props = defineProps({
    songs: {
        type: Array,
        default() {
          return []
        }
      },
      rank: Boolean
  })
  const emit = defineEmits(['select'])
  function getDesc(song) {
    return `${song.singer}·${song.album}`
  }
  function selectItem(song, index) {
    emit('select', { song, index })
  }
  function getRankCls(index) {
    if (index <= 2) {
      return `icon icon${index}`
    } else {
      return 'text'
    }
  }
  function getRankText(index) {
    if (index > 2) {
      return index + 1
    }
  }
</script>

<style lang="scss" scoped>
  .song-list {
    .item {
      display: flex;
      align-items: center;
      box-sizing: border-box;
      height: 64px;
      font-size: $font-size-medium;
      .rank {
        flex: 0 0 25px;
        width: 25px;
        margin-right: 20px;
        text-align: center;
        .icon {
          display: inline-block;
          width: 25px;
          height: 24px;
          background-size: 25px 24px;
          &.icon0 {
            @include bg-image('first');
          }
          &.icon1 {
            @include bg-image('second');
          }
          &.icon2 {
            @include bg-image('third');
          }
        }
        .text {
          color: $color-theme;
          font-size: $font-size-large;
        }
      }
      .content {
        flex: 1;
        line-height: 20px;
        overflow: hidden;
        .name {
          @include no-wrap();
          color: $color-text
        }
        .desc {
          @include no-wrap();
          margin-top: 4px;
          color: $color-text-d;
        }
      }
    }
  }
</style>
